### ISSUE TITLE
Getting an Error in iOS 

### ISSUE THREAD

**Issue by prameetchakraborty** [doowb/firebase-cron#9]
![screen shot 2018-05-17 at 5 03 05 pm](https://user-images.githubusercontent.com/29853903/40174994-6600052a-59f4-11e8-8720-46c88bbde56b.png)

**This is my initialisation code**

Firebase.initializeApp(firebaseConfig);

var ref = Firebase.database().ref();
var queueRef = Firebase.database().ref('queue');
var options = {endpoint: 'jobs'};

var cron = new Cron(ref, queueRef, options);

**this is inside my ComponentDidMount()**

    cron.addJob('test', '1 * * * * *', {foo: 'bar'}, function(err) {
      if(err) return console.error(err);
      console.log('job added');
    })

    cron.getJobs(function(err,jobs) {
      console.log('err', err, 'jobs', jobs);
    })

    cron.status(function(status) {
      console.log('status', status);
    })`

**I am using Cloud Firestore and not Realtime Database**

**Comment by doowb** [comment]
Thanks for the issue. You didn't provide this information, but I'm assuming that you're trying to use this package in `react-native` and bundle it with `webpack`?

Since `webpack` has a bug that causes it to say `require` is being misused... you'll need to configure `webpack` to use [unlazy-loader](https://github.com/doowb/unlazy-loader). For what it's worth... I started on a refactor a couple of weeks ago that simplifies how the dependencies are required in.

> cron.status

Unless you added that, there isn't a `.status` method in this package.

> I am using Cloud Firestore and not Realtime Database

This package is for the Realtime Database since it was written well before that and the intended use is to use with `firebase-queue` which is also written for the Realtime Database, however, another part of the refactor is to remove the dependency on `firebase-queue` (it shouldn't actually be a dependency anyway) and all implementors (like you) to choose what happens when a job is run, e.g. put the data into a `firebase-queue` ref like now, put the data someplace else (maybe in a Firestore collection), call an https firebase cloud function (or any url), etc...

BTW... it's interesting to know if this works on iOS (I'm guessing that it's just for a UI to manage jobs, but there is a server that's actually running them).

**Comment by prameetchakraborty** [comment]
Yes, this is `react-native` with `webpack`. So does this mean that this package is not compatible with Cloud Firestore for now?

**Comment by doowb** [comment]
> So does this mean that this package is not compatible with Cloud Firestore for now?

Correct, in the terms that it uses the Realtime Database to store data. It can be used in a project that users Cloud Firestore and you can access both from the same code if necessary.

**Comment by prameetchakraborty** [comment]
Cool, thanks a lot. So, I guess I just need to configure the unlazy-loader part.

**Comment by doowb** [comment]
Yes

**Comment by prameetchakraborty** [comment]
Sorry, I made a mistake. I am using `babel` for bundling. I have a `.babelrc` file in my folder.

**Comment by doowb** [comment]
I didn't know that `babel` did bundling, I thought it only transpiled. I'm not as familiar with how that would work in `babel`.

One thing you can do is go into your `node_modules` and change this file to the follow:

> node_modules/firebase-cron/lib/utils.js

```js
'use strict';

exports.async = require('async');
exports.cron = require('cron');
exports.extend = require('extend-shallow');
exports.firebase = require('firebase');
exports.Queue = require('firebase-queue');
exports.moment = require('moment');

var remoteDate = null;
exports.remoteDate = function(ref) {
  if (remoteDate) return remoteDate;

  var offset = 0;
  ref.child('/.info/serverTimeOffset').on('value', function(snapshot) {
    offset = snapshot.val() || 0;
  });

  remoteDate = function() {
    return Date.now() + offset;
  };

  return remoteDate;
};
```

This is essentially what `unlazy-loader` would do. This is only a temporary fix until I push up the refactor.

**Comment by prameetchakraborty** [comment]
Cool, Thanks a lot for the help @doowb

**Comment by doowb** [comment]
I published what I had done so far... it was mostly updating to newer javascript and cleaning up code. The api works with promises instead of async callbacks now. I'm going to close this issue, but let me know if you still have issues bundling.

**Comment by prameetchakraborty** [comment]
Sure, will notify. Thanks :-)

**Comment by prameetchakraborty** [comment]
Hey @doowb, I am facing this issue now after replacing the new code in utils.js.

Unable to resolve module `child_process` from 
`project/node_modules/cron/lib/cron.js`: Module does not exist in the module map

I think this is an issue with the 'cron' npm package that this package is using. Could you please help me out?

**Comment by doowb** [comment]
I published a new version, have you tried that?

**Comment by prameetchakraborty** [comment]
I did npm install firebase-cron, I am getting the same error.

**Comment by doowb** [comment]
you probably need to force npm to get the latest: `npm install firebase-cron@latest` since you had `0.1.2` installed previously. You should get `1.0.1` now.

**Comment by prameetchakraborty** [comment]
Cool, or maybe i can just fork it. Then it will be the latest version.

**Comment by doowb** [comment]
> maybe i can just fork it. Then it will be the latest version.

That will give you the latest code on GitHub, and you're welcome to do that. However, the latest version published to NPM removed the issue you had with how `require` was being used and is using a different dependency that doesn't use `child_process` so your new issue should go away.

Also, by doing `npm install firebase-cron@latest` should force npm to install the latest version. Sometimes npm doesn't always do what you think it will do. I also use `npm cache clear --force` a lot to ensure the latest versions of code are downloaded.

**Comment by prameetchakraborty** [comment]
Cool, thanks a lot for the update.

**Comment by prameetchakraborty** [comment]
Yeah, it's working. Thanks a lot!

I see a sample code 

```cron.addJob('test', '00 * * * * *', {foo: 'bar'}, function(err) {
  if (err) return console.error(err);
  console.log('job added');
  console.log();``` 

So, this should print 'Job Added' in my console immediately right? I mean within the next minute.
